config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong>. The data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            Steven
            <br />
            Universe
            <br />
            Quotes
          </div>
        <% end %>
      </div>

      <div class="col-4 hidden-sx-down slogan">
        All hail sucrose.
      </div>

      <div class="col-10 offset-1 offset-1 offset-sm-0 col-sm-5 links">
        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About', about_path %>
      </div>

    </header>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute your quote.</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "What is the quote you want to add?", placeholder: "We are the Crystal Gems." %>
              <br />
              <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Steven Universe" %>
              <br />
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            
          </div>
        </div>
      </div>
    </div>

    <hr />

    <br class="clear"/>

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class ="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "Give me another quote.", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Created by B.K., meep-morp connoisseur.
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1">
  <h1>About Splurty</h1>

  <p>
    Splurty was built by <a target="_blank" href="http://github.com/MarcoMorawec">Marco</a> & <a target="_blank" href="http://github.com/KenMazaika">Ken</a>. Two web developers who are on a mission to give people the technical skills needed to launch their own MVPs and turn ideas into reality.
  </p>
  <br />
  <p>
    Together they taught hundreds of students how to code and build products people want at places like Harvard Business School, Carnegie Mellon, Babson, Rhode Island School of Design, Brown University, Punohou High School and ‘Iolani High School.
  </p>
  <p>
    If you want to learn how to code - start <a target="_blank" href="https://online.bootcampspot.com"> here</a>.
  </p>


  <div class="row">
    <div class="col-12 col-sm-4">
      <%= image_tag 'dan_vineyard.jpeg', class: 'img-fluid fixImage' %>
    </div>

    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center">Marco Morawec</h2>
      <br />
      <p>
        Marco Morawec is a web developer and user experience product manager. He consulted Fortune 500 companies like P&G and John Deere, won Boston's biggest Hackathon (<a target="_blank" href="http://www.angelhack.com/">Angelhack</a>) and most recently led the user experience for <a target="_blank" href="https://www.peertransfer.com/">peerTransfer</a>, building a $500M/year international tuition payment platform. In an earlier life, he travelled around the world on <a target="_blank" href="http://25dollartravel.com">$25/day</a> for an entire year.
      </p>
    </div>
  </div>
  <br class="clear" />

  <div class="row">
    <div class="col-12 col-sm-4" style="padding-top:30px;">
      <%= image_tag 'dan_boat_lucerne.jpg', class: 'img-fluid fixImage' %>
    </div>
    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center">Ken Mazaika</h2>
      <br />
      <p>
        Ken Mazaika is a web developer and Ruby on Rails contributor. Previously he was a tech lead at Where.com (<a target="_blank" href="http://bostinno.streetwise.co/2011/04/13/nearbuys-where-rolls-out-daily-deals/">acquired by PayPal</a>) and a member of the PayPal/eBay development team in Boston. In a previous life he turned a <a target="_blank" href="http://yourfreequotes.com/">health insurance quotes generator</a> from a $400/day web application into a $40,000/day business.
      </p>
    </div>
  </div>

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span>Quote / No. <%= @quote.id %></span>
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />
<br />